let ventasOnline = [
    {id: 1, nombre: "Lubricante", tipo: "Aceite para Motor", desc: "Shell Helix 10W40", precio: 27000, img: '/img/ventaOnline/aceite.jpg'}, 
    {id: 2, nombre: "Lubricante", tipo: "Aceite para Motor", desc: "Liqui Moly 10W40", precio: 29000, img: '/img/ventaOnline/aceite2.jpg'}, 
    {id: 3, nombre: "Anticongelate", tipo: "AguaRadiador", desc: "Anticongelate Prestone", precio: 5500, img: '/img/ventaOnline/anticongelante.jpg'}, 
    {id: 4, nombre: "Anticongelate", tipo: "AguaRadiador", desc: "Anticongelante AutoStyle", precio: 4500, img: '/img/ventaOnline/anticongelante2.jpg'}, 
    {id: 5, nombre: "Cable", tipo: "CablePuente", desc: "Cable para hacer puente", precio: 3500, img: '/img/ventaOnline/cable.jpg'}, 
    {id: 6, nombre: "Cargador", tipo: "CargadorUSB", desc: "Cargador USB Universal", precio: 4500, img: '/img/ventaOnline/cargador.jpg'}, 
    {id: 7, nombre: "Lavaparabrisas", tipo: "Lavaparabrisas", desc: "Vistony Multiusos", precio: 4500, img: '/img/ventaOnline/aguaparabrisas2.jpg'}, 
    {id: 8, nombre: "Lavaparabrisas", tipo: "Lavaparabrisas", desc: "Prestone Bug Wash", precio: 3500, img: '/img/ventaOnline/aguaparabrisas.jpg'}, 
    {id: 9, nombre: "Cera", tipo: "Cera", desc: "Cera Crema Kit", precio: 2500, img: '/img/ventaOnline/cera.jpg'}, 
    {id: 10, nombre: "Cera", tipo: "Cera", desc: "Cera Líquida Carnauba", precio: 3500, img: '/img/ventaOnline/cera2.jpg'}, 
    {id: 11, nombre: "Esponja", tipo: "Esponja", desc: "Esponja Kleaner", precio: 1500, img: '/img/ventaOnline/esponja.jpg'}, 
    {id: 12, nombre: "Esponja", tipo: "Esponja", desc: "Esponja Momo", precio: 2500, img: '/img/ventaOnline/esponja2.jpg'}, 
    {id: 13, nombre: "Liquido", tipo: "Liquido", desc: "Liquido Liqui Moly", precio: 3500, img: '/img/ventaOnline/liquido.jpg'}, 
    {id: 14, nombre: "Liquido", tipo: "Liquido", desc: "Liquido Wagner", precio: 4500, img: '/img/ventaOnline/liquido2.jpg'}, 
    {id: 15, nombre: "Aromático", tipo: "Aromático", desc: "Pino Little Trees", precio: 2300, img: '/img/ventaOnline/pino.jpg'}, 
    {id: 16, nombre: "Aromático", tipo: "Aromático", desc: "Universo Garden Angels", precio: 3200, img: '/img/ventaOnline/pino2.jpg'}, 
    {id: 17, nombre: "Silicona", tipo: "Silicona", desc: "Silicona Kit", precio: 4500, img: '/img/ventaOnline/silicona.jpg'}, 
    {id: 18, nombre: "Silicona", tipo: "Silicona", desc: "Silicona Saniclean", precio: 3500, img: '/img/ventaOnline/silicona2.jpg'}, 
    {id: 19, nombre: "Cinturón", tipo: "Cinturón", desc: "Cinturón de Seguridad Mascotas", precio: 2300, img: '/img/ventaOnline/cinturon.jpg'}, 
    {id: 20, nombre: "Kit", tipo: "Kit", desc: "Kit de Emergencias", precio: 5800, img: '/img/ventaOnline/kit.jpg'}, 
    {id: 21, nombre: "Corrosivo", tipo: "Corrosivo", desc: "Lubricante Antocorrosivo WD-40", precio: 4900, img: '/img/ventaOnline/lubricante.jpg'}, 
    {id: 22, nombre: "Soporte", tipo: "Soporte", desc: "Soporte Telefono Automovil", precio: 3500, img: '/img/ventaOnline/soporte.jpg'}
]